### ISSUE TITLE
Image::save must return ImageInterface

### ISSUE THREAD

**Issue by batyrmastyr** [rokka-io/imagine-vips#13]
Currently, with VIPS 8.9 empty array is returned.
https://github.com/rokka-io/imagine-vips/blob/5cd6490121686aa938715839f6c6abb282e859c7/lib/Imagine/Vips/Image.php#L427-L442

Additionally, `Layers::coalesce` return nothing instead of self.
And one more thing: there are `public const` declarations. They were introduced in php 7.1, but php 7.0 is required.

Oh, `Effects::modulate` returns inexistent `RokkaImageInterface`.

**Comment by batyrmastyr** [comment]
@chregu bump

**Comment by chregu** [comment]
The main issues (with PHP 8.1 and some other type mismatches) were fixed in #27 - The others (adding types everywhere) we won't fix due to too many BC issues.

**Comment by batyrmastyr** [comment]
@chregu looks like the main bug fix is missing: [this change](https://github.com/rokka-io/imagine-vips/pull/14/files#diff-f8930eef7b86e4eccaaae4f85a6a76ff07bbca92f57b6568eb5939179df2ea9aR441-R442) in `Image::save`

```php
try {
-                 return $vips->$method($path, $saveOptions);

+                 $vips->$method($path, $saveOptions);
+                 return $this;
             }
```
Current code returns a result of calling `jpegsave`, `pngsave` and other *save `vips-php` methods instead of declared `ImageInterface`. And it looks like the same adjustment should be done in `Image::get`.

**Comment by chregu** [comment]
Thanks for that. It's fixed in master. `image::get` should return a "string" with the image content, that is correct.
