### ISSUE TITLE
Broken link “magicksave” in readme

### ISSUE THREAD

**Issue by ausi** [rokka-io/imagine-vips#19]
The “magicksave” link in the readme seems to be broken: https://github.com/rokka-io/imagine-vips/blob/b66966d2a6203684371290d9c4000928d10d672d/README.md#L59

It should probably link here I think: <https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-magicksave>

**Comment by chregu** [comment]
thanks. should be fixed now.
