### ISSUE TITLE
Issue with loading animated webp

### ISSUE THREAD

**Issue by andi-eisenmann** [rokka-io/imagine-vips#35]
For the loaders `VipsForeignLoadWebpFile` and `VipsForeignLoadWebpBuffer` the `n`-Option is not being applied so no animated webp can be loaded:

https://github.com/rokka-io/imagine-vips/blob/0.31.0/lib/Imagine/Vips/Imagine.php#L237

I think there should also be those two cases:

```php
            case 'VipsForeignLoadWebpFile':
            case 'VipsForeignLoadWebpBuffer':
                $options['n'] = -1; // not sure this should be enabled by default, to discuss
                break;
```

When I add those lines, i can open animated webp images without any problems. Otherwise only the first frame will be loaded, so the animation will "get lost".

**Comment by chregu** [comment]
Thanks. Fixed in https://github.com/rokka-io/imagine-vips/commit/b50018802f0b8d4989c642cc93bf1e0e2e5f769b
